import {
  Geist,
  Geist_Mono,
  Inter,
  Archivo,
  Nunito_Sans,
} from "next/font/google";
import "./globals.css";
import Header from "../components/organisms/Header";
import { ThemeProvider } from "@/components/templates/templates/ThemeProvider";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/redux/provider";
import SessionExpiredModal from "@/components/common/SessionExpiredModal";
import "remixicon/fonts/remixicon.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-archivo",
});

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-nunito",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${archivo.variable} ${nunito.variable}`}
    >
      <body className={`${geistSans.variable}`}>
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            duration: 3000,
          }}
        />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReduxProvider>
            <SessionExpiredModal />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
